using NUnit.Framework;
using Rhino;
using Rhino.DocObjects;
using Rhino.FileIO;
using Rhino.Geometry;
using System;
using System.Drawing;
using System.IO;

namespace FileIO
{
  /// <summary>
  /// Authors the committed DXF import corpus in <c>models\DXFfile\</c> and the export suite's
  /// purpose-made <c>.3dm</c> source in <c>models\DXFfile-export\</c>.
  /// </summary>
  /// <remarks>
  /// Same policy as <see cref="AuthorIgesCorpus"/>: generated by Rhino's own writer from geometry
  /// stated here - unencumbered, reviewable, reproducible - at the cost of exercising only Rhino's
  /// own DXF dialect (AC1032 by default). Externally-originated files (AutoCAD, LibreCAD, QCAD)
  /// belong in the corpus as they become available with clean rights, or in
  /// <c>private_models\models\DXFfile\</c>.
  ///
  /// Deliberately absent: an ExportMeshesAs=ThreeDFace variant - the managed side serializes
  /// "ThreeDFace" where the native side matches only "ThreeDFaces", so the option silently falls
  /// through to lines and a model named for it would lie. Add it when RH-98711 is fixed.
  ///
  /// [Explicit] twice over; refuses to run without MX_DXF_AUTHOR_OUT_DIR:
  /// <code>
  /// MX_DXF_AUTHOR_OUT_DIR=models dotnet test --filter "FullyQualifiedName~AuthorDxfCorpus"
  /// </code>
  /// Then regenerate baselines (MX_DXF_REGEN=*, MX_DXFEXPORT_REGEN=*), review every sidecar, and
  /// commit models and sidecars together.
  /// </remarks>
  [TestFixture, Explicit]
  public class AuthorDxfCorpus
  {
    [Test, Explicit]
    public void Write()
    {
      string outDir = System.Environment.GetEnvironmentVariable("MX_DXF_AUTHOR_OUT_DIR");
      Assert.IsFalse(string.IsNullOrWhiteSpace(outDir),
        "Set MX_DXF_AUTHOR_OUT_DIR to the repository's models folder. This test overwrites the " +
        "corpus, so it will not guess a path - see the remarks on AuthorDxfCorpus.");

      string importDir = Path.Combine(outDir, "DXFfile");
      string exportDir = Path.Combine(outDir, "DXFfile-export");
      Directory.CreateDirectory(importDir);
      Directory.CreateDirectory(exportDir);

      // 1. Bread-and-butter 2D entities: LINE, ARC, CIRCLE, LWPOLYLINE, POINT.
      Author(Path.Combine(importDir, "curves-2d-basics.dxf"), null, doc =>
      {
        doc.Objects.AddCurve(new LineCurve(new Point3d(0, 0, 0), new Point3d(20, 0, 0)));
        doc.Objects.AddCurve(new ArcCurve(new Arc(new Point3d(0, 10, 0), new Point3d(10, 18, 0), new Point3d(20, 10, 0))));
        doc.Objects.AddCurve(new ArcCurve(new Circle(new Plane(new Point3d(30, 5, 0), Vector3d.ZAxis), 4)));
        var pl = new Polyline(new Point3d[]
        {
          new Point3d(0, 25, 0), new Point3d(10, 25, 0), new Point3d(10, 35, 0), new Point3d(0, 35, 0), new Point3d(0, 25, 0)
        });
        doc.Objects.AddCurve(pl.ToPolylineCurve());
        doc.Objects.AddPoint(new Point3d(30, 25, 0));
      });

      // 2. SPLINE and ELLIPSE parsing, including a non-planar degree-3 curve.
      Author(Path.Combine(importDir, "splines-ellipse-3d.dxf"), null, doc =>
      {
        doc.Objects.AddCurve(NurbsCurve.Create(false, 3, new Point3d[]
        {
          new Point3d(0, 0, 0), new Point3d(6, 5, 4), new Point3d(14, -3, -3), new Point3d(20, 6, 2)
        }));
        doc.Objects.AddCurve(new Ellipse(new Plane(new Point3d(35, 0, 0), Vector3d.ZAxis), 8, 4).ToNurbsCurve());

        var pc = new PolyCurve();
        pc.AppendSegment(new LineCurve(new Point3d(0, 20, 0), new Point3d(10, 20, 0)));
        pc.AppendSegment(new ArcCurve(new Arc(new Point3d(10, 20, 0), new Point3d(15, 24, 0), new Point3d(20, 20, 0))));
        doc.Objects.AddCurve(pc);
      });

      // 3. ACIS solids: the one import model where solids > 0 is plausible. Written with
      //    surfaces-as-solids so the writer emits 3DSOLID entities (the ConvertAcisBrep path).
      Author(Path.Combine(importDir, "solids-acis.dxf"),
        o => o.ExportSurfacesAs = FileDwgWriteOptions.ExportSurfaceMode.Solids, doc =>
      {
        doc.Objects.AddBrep(Brep.CreateFromBox(new BoundingBox(0, 0, 0, 20, 10, 5)));
        doc.Objects.AddBrep(Brep.CreateFromCylinder(
          new Cylinder(new Circle(new Plane(new Point3d(40, 0, 0), Vector3d.ZAxis), 6), 15), true, true));
      });

      // 4. Meshes survive DXF by default (polyface mesh) - the anti-IGES.
      Author(Path.Combine(importDir, "mesh-polyface.dxf"), null, doc =>
      {
        doc.Objects.AddMesh(Mesh.CreateFromBox(new BoundingBox(0, 0, 0, 15, 10, 6), 1, 1, 1));
        var strip = new Mesh();
        strip.Vertices.Add(0, 20, 0); strip.Vertices.Add(10, 20, 0);
        strip.Vertices.Add(10, 30, 2); strip.Vertices.Add(0, 30, 2);
        strip.Faces.AddFace(0, 1, 2, 3);
        strip.Normals.ComputeNormals();
        doc.Objects.AddMesh(strip);
      });

      // 5. Blocks, nested and repeated: DXF preserves assembly structure (BLOCKS + INSERT),
      //    the other anti-IGES. One definition is never inserted, feeding the
      //    ImportUnreferencedBlocks read option.
      Author(Path.Combine(importDir, "blocks-nested.dxf"), null, doc =>
      {
        int inner = doc.InstanceDefinitions.Add("Inner", "circle+line", Point3d.Origin,
          new GeometryBase[]
          {
            new ArcCurve(new Circle(new Plane(Point3d.Origin, Vector3d.ZAxis), 2)),
            new LineCurve(new Point3d(-2, 0, 0), new Point3d(2, 0, 0)),
          },
          new ObjectAttributes[] { new ObjectAttributes(), new ObjectAttributes() });

        var outerAtts = new ObjectAttributes();
        var innerRef = new InstanceReferenceGeometry(doc.InstanceDefinitions[inner].Id, Transform.Translation(4, 0, 0));
        int outer = doc.InstanceDefinitions.Add("Outer", "inner + arc", Point3d.Origin,
          new GeometryBase[]
          {
            innerRef,
            new ArcCurve(new Arc(new Point3d(-4, -2, 0), new Point3d(0, -4, 0), new Point3d(4, -2, 0))),
          },
          new ObjectAttributes[] { outerAtts, new ObjectAttributes() });

        doc.Objects.AddInstanceObject(inner, Transform.Translation(0, 10, 0));
        doc.Objects.AddInstanceObject(inner, Transform.Multiply(
          Transform.Translation(12, 10, 0), Transform.Rotation(0.5, Vector3d.ZAxis, Point3d.Origin)));
        doc.Objects.AddInstanceObject(outer, Transform.Translation(24, 10, 0));

        // Never inserted: exists only as a definition.
        doc.InstanceDefinitions.Add("Unused", "never inserted", Point3d.Origin,
          new GeometryBase[] { new LineCurve(new Point3d(0, 0, 0), new Point3d(1, 1, 0)) },
          new ObjectAttributes[] { new ObjectAttributes() });
      });

      // 6. Nested layers (Parent$Child names under FullLayerPath=true) and colors.
      Author(Path.Combine(importDir, "layers-colors.dxf"), null, doc =>
      {
        int parent = doc.Layers.Add("Parent", Color.SteelBlue);
        var child = new Layer { Name = "Child", ParentLayerId = doc.Layers[parent].Id, Color = Color.Firebrick };
        int childIndex = doc.Layers.Add(child);

        doc.Objects.AddCurve(new LineCurve(new Point3d(0, 0, 0), new Point3d(10, 0, 0)),
          new ObjectAttributes { LayerIndex = parent });
        doc.Objects.AddCurve(new LineCurve(new Point3d(0, 5, 0), new Point3d(10, 5, 0)),
          new ObjectAttributes { LayerIndex = childIndex });
        doc.Objects.AddCurve(new LineCurve(new Point3d(0, 10, 0), new Point3d(10, 10, 0)),
          new ObjectAttributes
          {
            LayerIndex = childIndex,
            ColorSource = ObjectColorSource.ColorFromObject,
            ObjectColor = Color.FromArgb(0, 128, 64),
          });
      });

      // 7. Annotation: TEXT, a linear dimension and a solid hatch - the dimstyle and
      //    hatch-scale conversion paths.
      Author(Path.Combine(importDir, "text-dims-hatch.dxf"), null, doc =>
      {
        doc.Objects.AddText(new Rhino.Display.Text3d("mx dxf", new Plane(new Point3d(0, 0, 0), Vector3d.ZAxis), 3));

        var dim = LinearDimension.Create(AnnotationType.Aligned, doc.DimStyles.Current,
          new Plane(new Point3d(0, -10, 0), Vector3d.ZAxis),
          Vector3d.XAxis, new Point3d(0, -10, 0), new Point3d(20, -10, 0), new Point3d(10, -6, 0), 0.0);
        doc.Objects.AddLinearDimension(dim);

        var circle = new Circle(new Plane(new Point3d(30, 0, 0), Vector3d.ZAxis), 5);
        Hatch[] hatches = Hatch.Create(circle.ToNurbsCurve(), 0, 0, 1, 0.001);
        Assert.IsNotNull(hatches, "Hatch.Create failed while authoring text-dims-hatch.dxf");
        foreach (Hatch h in hatches) doc.Objects.AddHatch(h);
      });

      // 8. Expected failure: a structurally valid DXF whose ENTITIES section is empty - imports
      //    with zero objects, which the runner treats as failure, and the '!' prefix expects that.
      //    Hand-written text: ODA recovery cannot 'fix' an empty file into having objects.
      File.WriteAllText(Path.Combine(importDir, "!empty-entities.dxf"),
        "  0\r\nSECTION\r\n  2\r\nHEADER\r\n  9\r\n$ACADVER\r\n  1\r\nAC1015\r\n  0\r\nENDSEC\r\n" +
        "  0\r\nSECTION\r\n  2\r\nENTITIES\r\n  0\r\nENDSEC\r\n  0\r\nEOF\r\n");

      // ----- Export source: the Rhino-native cases tuned to DXF's loss profile. -----
      AuthorExportSource3dm(Path.Combine(exportDir, "rhino-native-mix-dxf.3dm"));
    }

    static void Author(string outPath, Action<FileDwgWriteOptions> configure, Action<RhinoDoc> build)
    {
      RhinoDoc doc = RhinoDoc.CreateHeadless(null);
      try
      {
        doc.ModelUnitSystem = UnitSystem.Millimeters;
        doc.ModelAbsoluteTolerance = 0.001;

        build(doc);
        Assert.Greater(doc.Objects.Count, 0, $"nothing was built for '{outPath}'.");

        var options = new FileDwgWriteOptions();
        configure?.Invoke(options);

        Assert.IsTrue(FileDwg.Write(outPath, doc, options), $"FileDwg.Write('{outPath}') returned false.");

        TestContext.Progress.WriteLine(
          $"[MXDXF] wrote '{outPath}': {doc.Objects.Count} objects, {new FileInfo(outPath).Length} bytes.");
      }
      finally
      {
        doc.Dispose();
      }
    }

    static void AuthorExportSource3dm(string outPath)
    {
      RhinoDoc doc = RhinoDoc.CreateHeadless(null);
      try
      {
        doc.ModelUnitSystem = UnitSystem.Millimeters;
        doc.ModelAbsoluteTolerance = 0.001;

        int solids = doc.Layers.Add("Solids", Color.SteelBlue);
        int wires = doc.Layers.Add("Wires", Color.Firebrick);
        int facets = doc.Layers.Add("Facets", Color.SeaGreen);
        int notes = doc.Layers.Add("Notes", Color.DarkSlateGray);

        // A closed solid and an open trimmed surface: under the default surfacetype=curves both
        // collapse to wireframe - the single most instructive DXF default-behaviour baseline
        // (srcbreps N -> breps 0, curves > 0).
        doc.Objects.AddBrep(
          Brep.CreateFromBox(new BoundingBox(0, 0, 0, 20, 10, 5)),
          new ObjectAttributes { LayerIndex = solids });
        var circle = new Circle(new Plane(new Point3d(40, 5, 0), Vector3d.ZAxis), 6);
        Brep[] trimmed = Brep.CreatePlanarBreps(new Curve[] { circle.ToNurbsCurve() }, 0.001);
        Assert.IsNotNull(trimmed, "CreatePlanarBreps failed while authoring rhino-native-mix-dxf.3dm");
        foreach (Brep b in trimmed) doc.Objects.AddBrep(b, new ObjectAttributes { LayerIndex = solids });

        // An extrusion, feeding WriteThickCurves and the surfaces-as expansion.
        doc.Objects.AddExtrusion(
          Extrusion.Create(
            new Circle(new Plane(new Point3d(70, 0, 0), Vector3d.ZAxis), 4).ToNurbsCurve(), 12, true),
          new ObjectAttributes { LayerIndex = solids });

        // A mesh: survives DXF as a polyface mesh (srcmeshes 1 -> meshes 1), the inverse of IGES.
        doc.Objects.AddMesh(
          Mesh.CreateFromBox(new BoundingBox(0, 30, 0, 15, 40, 6), 1, 1, 1),
          new ObjectAttributes { LayerIndex = facets });

        // One of each curve species, so the per-type Export*As knobs have distinct victims.
        doc.Objects.AddCurve(new LineCurve(new Point3d(0, 50, 0), new Point3d(20, 50, 0)),
          new ObjectAttributes { LayerIndex = wires });
        doc.Objects.AddCurve(
          new ArcCurve(new Arc(new Point3d(25, 50, 0), new Point3d(30, 54, 0), new Point3d(35, 50, 0))),
          new ObjectAttributes { LayerIndex = wires });
        doc.Objects.AddCurve(NurbsCurve.Create(false, 3, new Point3d[]
        {
          new Point3d(40, 50, 0), new Point3d(46, 55, 3), new Point3d(54, 47, -2), new Point3d(60, 53, 0)
        }), new ObjectAttributes { LayerIndex = wires });
        var pl = new Polyline(new Point3d[]
        {
          new Point3d(0, 60, 0), new Point3d(10, 60, 0), new Point3d(10, 70, 0)
        });
        doc.Objects.AddCurve(pl.ToPolylineCurve(), new ObjectAttributes { LayerIndex = wires });
        var pc = new PolyCurve();
        pc.AppendSegment(new LineCurve(new Point3d(20, 60, 0), new Point3d(30, 60, 0)));
        pc.AppendSegment(new ArcCurve(new Arc(new Point3d(30, 60, 0), new Point3d(35, 64, 0), new Point3d(40, 60, 0))));
        doc.Objects.AddCurve(pc, new ObjectAttributes { LayerIndex = wires });

        // A point, text and a linear dimension: annotation loss/survival.
        doc.Objects.AddPoint(new Point3d(70, 60, 0), new ObjectAttributes { LayerIndex = wires });
        doc.Objects.AddText(new Rhino.Display.Text3d("mx dxf src", new Plane(new Point3d(0, 80, 0), Vector3d.ZAxis), 3),
          new ObjectAttributes { LayerIndex = notes });
        var dim = LinearDimension.Create(AnnotationType.Aligned, doc.DimStyles.Current,
          new Plane(new Point3d(0, 90, 0), Vector3d.ZAxis),
          Vector3d.XAxis, new Point3d(0, 90, 0), new Point3d(20, 90, 0), new Point3d(10, 94, 0), 0.0);
        doc.Objects.AddLinearDimension(dim, new ObjectAttributes { LayerIndex = notes });

        // A block inserted twice: DXF keeps blocks (srcinstances 2 -> instances 2), unlike IGES.
        int idef = doc.InstanceDefinitions.Add(
          "Peg", "A pin, instanced twice", Point3d.Origin,
          new GeometryBase[]
          {
            new ArcCurve(new Circle(new Plane(Point3d.Origin, Vector3d.ZAxis), 2)),
          },
          new ObjectAttributes[] { new ObjectAttributes { LayerIndex = wires } });

        doc.Objects.AddInstanceObject(idef, Transform.Translation(0, 105, 0));
        doc.Objects.AddInstanceObject(idef, Transform.Translation(12, 105, 0));

        // SuppressAllInput/SuppressDialogBoxes are not optional here. RhinoDoc.WriteFile over an
        // EXISTING .3dm asks the user something; without them this [Explicit] author does not
        // fail, it blocks forever, and the blocked test host cannot be killed with Stop-Process
        // -Force or taskkill /F /T - the machine needs a reboot to clear it. Writing to a fresh
        // folder hides this, which is exactly how it stayed hidden until a re-author.
        Assert.IsTrue(doc.WriteFile(outPath, new FileWriteOptions { FileVersion = 7, SuppressAllInput = true, SuppressDialogBoxes = true }),
          $"RhinoDoc.WriteFile('{outPath}') returned false.");

        TestContext.Progress.WriteLine(
          $"[MXDXFEX] wrote '{outPath}': {doc.Objects.Count} objects, {new FileInfo(outPath).Length} bytes. " +
          "Regenerate its baseline next: MX_DXFEXPORT_REGEN=rhino-native-mix-dxf.");
      }
      finally
      {
        doc.Dispose();
      }
    }
  }
}
