using NUnit.Framework;
using Rhino;
using Rhino.FileIO;
using Rhino.Geometry;
using System;
using System.IO;

namespace FileIO
{
  /// <summary>
  /// Authors the committed STL import corpus in <c>models\STLfile\</c> and the export suite's
  /// purpose-made <c>.3dm</c> source in <c>models\STLfile-export\</c>.
  /// </summary>
  /// <remarks>
  /// Same policy as the IGES/DXF/DWG authors: generated by Rhino's own writer from geometry stated
  /// here, so the corpus is unencumbered and reproducible, at the cost of exercising the reader
  /// only on Rhino's own output. One model breaks that rule deliberately - the hand-written ASCII
  /// tetrahedron below is not Rhino's formatting, so the text parser is exercised on something it
  /// did not produce.
  ///
  /// STL is the thinnest format in the suite: triangles and nothing else. No units (the file
  /// carries none, which is why the reader's STLModelUnits option exists - and why it being dead
  /// matters, see the guide), no layers, no colors, no assembly structure, no curves or
  /// annotations. Everything meshable becomes one body; everything else is dropped silently.
  ///
  /// [Explicit] twice over; refuses to run without MX_STL_AUTHOR_OUT_DIR:
  /// <code>
  /// MX_STL_AUTHOR_OUT_DIR=models dotnet test --filter "FullyQualifiedName~AuthorStlCorpus"
  /// </code>
  /// Then MX_STL_REGEN=*, MX_STLEXPORT_REGEN=*, read every sidecar, commit models and sidecars
  /// together.
  /// </remarks>
  [TestFixture, Explicit]
  public class AuthorStlCorpus
  {
    [Test, Explicit]
    public void Write()
    {
      string outDir = System.Environment.GetEnvironmentVariable("MX_STL_AUTHOR_OUT_DIR");
      Assert.IsFalse(string.IsNullOrWhiteSpace(outDir),
        "Set MX_STL_AUTHOR_OUT_DIR to the repository's models folder. This test overwrites the " +
        "corpus, so it will not guess a path - see the remarks on AuthorStlCorpus.");

      string importDir = Path.Combine(outDir, "STLfile");
      string exportDir = Path.Combine(outDir, "STLfile-export");
      Directory.CreateDirectory(importDir);
      Directory.CreateDirectory(exportDir);

      // 1. Binary box: the minimal binary path. Closed, so the baseline pins solids 1 and an
      //    exact volume - the arithmetic check that nothing was lost in the triangle soup.
      Author(Path.Combine(importDir, "stl-binary-box.stl"), true, doc =>
      {
        doc.Objects.AddMesh(Mesh.CreateFromBox(new BoundingBox(0, 0, 0, 10, 8, 5), 1, 1, 1));
      });

      // 2. The same box as ASCII: the other on-disk variant through the same reader. Its baseline
      //    should match stl-binary-box's exactly - same geometry, different encoding.
      Author(Path.Combine(importDir, "stl-ascii-box.stl"), false, doc =>
      {
        doc.Objects.AddMesh(Mesh.CreateFromBox(new BoundingBox(0, 0, 0, 10, 8, 5), 1, 1, 1));
      });

      // 3. Two disjoint bodies in one binary STL. STL has no concept of separate objects, so this
      //    pins the reader's SplitDisjointMeshes=true default putting them back into two meshes.
      Author(Path.Combine(importDir, "stl-two-bodies.stl"), true, doc =>
      {
        doc.Objects.AddMesh(Mesh.CreateFromBox(new BoundingBox(0, 0, 0, 8, 8, 8), 1, 1, 1));
        doc.Objects.AddMesh(Mesh.CreateFromBox(new BoundingBox(20, 0, 0, 28, 8, 8), 1, 1, 1));
      });

      // 4. A faceted sphere: many triangles, and the Weld=true / WeldAngle=22.5 defaults doing
      //    real work on a curved surface rather than on box corners.
      Author(Path.Combine(importDir, "stl-sphere.stl"), true, doc =>
      {
        doc.Objects.AddMesh(Mesh.CreateFromSphere(new Sphere(new Point3d(5, 5, 5), 5), 16, 12));
      });

      // 5. Hand-written ASCII tetrahedron - deliberately NOT Rhino's own output: a named solid,
      //    indented free-form whitespace, normals that are not unit vectors. The reader should
      //    not care about any of that.
      //
      //    Winding matters and is easy to get wrong by hand: the four corners are (0,0,0),
      //    (10,0,0), (0,10,0) and the apex (5,5,8), so the enclosed volume is
      //    |det| / 6 = 800 / 6 = 133.333... The facets below are wound counter-clockwise seen
      //    from OUTSIDE, which is what makes that volume come out positive. Wound the other way
      //    the mesh still reads as closed and still measures 133.333, but negative - and a
      //    baseline pinning a negative volume would be pinning this file's mistake rather than
      //    the reader's behaviour.
      File.WriteAllText(Path.Combine(importDir, "stl-ascii-handmade.stl"),
        "solid handmade\r\n" +
        "  facet normal 0 0 -1\r\n" +
        "    outer loop\r\n      vertex 0 0 0\r\n      vertex 0 10 0\r\n      vertex 10 0 0\r\n    endloop\r\n" +
        "  endfacet\r\n" +
        "  facet normal 0 -1 0\r\n" +
        "    outer loop\r\n      vertex 0 0 0\r\n      vertex 10 0 0\r\n      vertex 5 5 8\r\n    endloop\r\n" +
        "  endfacet\r\n" +
        "  facet normal -1 0 0\r\n" +
        "    outer loop\r\n      vertex 0 0 0\r\n      vertex 5 5 8\r\n      vertex 0 10 0\r\n    endloop\r\n" +
        "  endfacet\r\n" +
        "  facet normal 1 1 1\r\n" +
        "    outer loop\r\n      vertex 10 0 0\r\n      vertex 0 10 0\r\n      vertex 5 5 8\r\n    endloop\r\n" +
        "  endfacet\r\n" +
        "endsolid handmade\r\n");

      // ----- Export source -----
      AuthorExportSource3dm(Path.Combine(exportDir, "rhino-native-mix-stl.3dm"));
    }

    static void Author(string outPath, bool binary, Action<RhinoDoc> build)
    {
      RhinoDoc doc = RhinoDoc.CreateHeadless(null);
      try
      {
        doc.ModelUnitSystem = UnitSystem.Millimeters;
        doc.ModelAbsoluteTolerance = 0.001;

        build(doc);
        Assert.Greater(doc.Objects.Count, 0, $"nothing was built for '{outPath}'.");

        // ExportOpenObjects stays true everywhere: false plus open geometry raises a modal error
        // dialog, which in a headless authoring run would hang rather than fail.
        var options = new FileStlWriteOptions { BinaryFile = binary, ExportOpenObjects = true };
        Assert.IsTrue(FileStl.Write(outPath, doc, options), $"FileStl.Write('{outPath}') returned false.");

        TestContext.Progress.WriteLine(
          $"[MXSTL] wrote '{outPath}': {doc.Objects.Count} objects, {new FileInfo(outPath).Length} bytes, " +
          (binary ? "binary." : "ascii."));
      }
      finally
      {
        doc.Dispose();
      }
    }

    static void AuthorExportSource3dm(string outPath)
    {
      RhinoDoc doc = RhinoDoc.CreateHeadless(null);
      try
      {
        doc.ModelUnitSystem = UnitSystem.Millimeters;
        doc.ModelAbsoluteTolerance = 0.001;

        // A closed brep box: the writer meshes it, so the round trip shows brep -> mesh.
        doc.Objects.AddBrep(Brep.CreateFromBox(new BoundingBox(0, 0, 0, 12, 8, 5)));

        // An extrusion: Rhino's lightweight solid, also meshed.
        doc.Objects.AddExtrusion(
          Extrusion.Create(new Circle(new Plane(new Point3d(30, 0, 0), Vector3d.ZAxis), 4).ToNurbsCurve(), 10, true));

        // A mesh: passes through as itself.
        doc.Objects.AddMesh(Mesh.CreateFromBox(new BoundingBox(50, 0, 0, 58, 8, 5), 1, 1, 1));

        // Everything below is dropped by the STL writer - the format cannot carry any of it.
        // The baseline records the drop as src counts against nothing on the way back.
        doc.Objects.AddCurve(new LineCurve(new Point3d(0, 20, 0), new Point3d(10, 20, 0)));
        doc.Objects.AddPoint(new Point3d(20, 20, 0));
        doc.Objects.AddText(
          new Rhino.Display.Text3d("mx stl src", new Plane(new Point3d(0, 30, 0), Vector3d.ZAxis), 3));

        // SuppressAllInput/SuppressDialogBoxes are not optional here. RhinoDoc.WriteFile over an
        // EXISTING .3dm asks the user something; without them this [Explicit] author does not
        // fail, it blocks forever, and the blocked test host cannot be killed with Stop-Process
        // -Force or taskkill /F /T - the machine needs a reboot to clear it. Writing to a fresh
        // folder hides this, which is exactly how it stayed hidden until a re-author.
        Assert.IsTrue(doc.WriteFile(outPath, new FileWriteOptions { FileVersion = 7, SuppressAllInput = true, SuppressDialogBoxes = true }),
          $"RhinoDoc.WriteFile('{outPath}') returned false.");

        TestContext.Progress.WriteLine(
          $"[MXSTLEX] wrote '{outPath}': {doc.Objects.Count} objects, {new FileInfo(outPath).Length} bytes. " +
          "Regenerate its baseline next: MX_STLEXPORT_REGEN=rhino-native-mix-stl.");
      }
      finally
      {
        doc.Dispose();
      }
    }
  }
}
