using NUnit.Framework;
using Rhino;
using Rhino.DocObjects;
using Rhino.FileIO;
using Rhino.Geometry;
using System;
using System.Drawing;
using System.IO;

namespace FileIO
{
  /// <summary>
  /// Authors the committed DWG import corpus in <c>models\DWGfile\</c> and the export suite's
  /// <c>.3dm</c> source in <c>models\DWGfile-export\</c>.
  /// </summary>
  /// <remarks>
  /// Same policy as the IGES and DXF authors: generated by Rhino's own writer from geometry
  /// stated here. DWG and DXF share one plugin, but the corpora are deliberately fully separate
  /// (own models, own geometry) so the two suites never share a file.
  ///
  /// Deliberately absent, as in DXF: an ExportMeshesAs=ThreeDFace variant (the managed/native
  /// spelling gap silently exports lines instead). Simplify stays false everywhere so the dead
  /// SimplifyTolerance key is inert.
  ///
  /// [Explicit] twice over; refuses to run without MX_DWG_AUTHOR_OUT_DIR:
  /// <code>
  /// MX_DWG_AUTHOR_OUT_DIR=models dotnet test --filter "FullyQualifiedName~AuthorDwgCorpus"
  /// </code>
  /// Then MX_DWG_REGEN=*, MX_DWGEXPORT_REGEN=*, read every sidecar, commit models and sidecars
  /// together.
  /// </remarks>
  [TestFixture, Explicit]
  public class AuthorDwgCorpus
  {
    [Test, Explicit]
    public void Write()
    {
      string outDir = System.Environment.GetEnvironmentVariable("MX_DWG_AUTHOR_OUT_DIR");
      Assert.IsFalse(string.IsNullOrWhiteSpace(outDir),
        "Set MX_DWG_AUTHOR_OUT_DIR to the repository's models folder. This test overwrites the " +
        "corpus, so it will not guess a path - see the remarks on AuthorDwgCorpus.");

      string importDir = Path.Combine(outDir, "DWGfile");
      string exportDir = Path.Combine(outDir, "DWGfile-export");
      Directory.CreateDirectory(importDir);
      Directory.CreateDirectory(exportDir);

      // 1. The curve zoo: LINE, ARC, CIRCLE, ELLIPSE, SPLINE, POLYLINE + a polycurve under the
      //    SplitPolycurves=true default.
      Author(Path.Combine(importDir, "dwg-curve-zoo.dwg"), null, BuildCurveZoo);

      // 2. ACIS solids: box, capped cylinder, sphere as 3DSOLID entities.
      Author(Path.Combine(importDir, "dwg-acis-solids.dwg"),
        o => o.ExportSurfacesAs = FileDwgWriteOptions.ExportSurfaceMode.Solids, doc =>
      {
        doc.Objects.AddBrep(Brep.CreateFromBox(new BoundingBox(0, 0, 0, 18, 9, 6)));
        doc.Objects.AddBrep(Brep.CreateFromCylinder(
          new Cylinder(new Circle(new Plane(new Point3d(35, 0, 0), Vector3d.ZAxis), 5), 12), true, true));
        doc.Objects.AddBrep(Brep.CreateFromSphere(new Sphere(new Point3d(60, 5, 5), 5)));
      });

      // 3. The same box under the DEFAULT surfaces-as-curves: the headline default loss case
      //    (solid in, wireframe out).
      Author(Path.Combine(importDir, "dwg-surfaces-as-curves.dwg"), null, doc =>
      {
        doc.Objects.AddBrep(Brep.CreateFromBox(new BoundingBox(0, 0, 0, 18, 9, 6)));
      });

      // 4. Meshes as PolyFaceMesh entities.
      Author(Path.Combine(importDir, "dwg-mesh.dwg"), null, doc =>
      {
        doc.Objects.AddMesh(Mesh.CreateFromBox(new BoundingBox(0, 0, 0, 12, 8, 5), 1, 1, 1));
        var sphere = Mesh.CreateFromSphere(new Sphere(new Point3d(30, 4, 4), 4), 12, 8);
        doc.Objects.AddMesh(sphere);
      });

      // 5. Blocks: one definition inserted twice (one rotated+scaled) plus a nested block.
      Author(Path.Combine(importDir, "dwg-blocks.dwg"), null, doc =>
      {
        int inner = doc.InstanceDefinitions.Add("DwgInner", "square", Point3d.Origin,
          new GeometryBase[]
          {
            new Polyline(new Point3d[]
            {
              new Point3d(-1, -1, 0), new Point3d(1, -1, 0), new Point3d(1, 1, 0),
              new Point3d(-1, 1, 0), new Point3d(-1, -1, 0)
            }).ToPolylineCurve(),
          },
          new ObjectAttributes[] { new ObjectAttributes() });

        var innerRef = new InstanceReferenceGeometry(doc.InstanceDefinitions[inner].Id, Transform.Translation(3, 0, 0));
        int outer = doc.InstanceDefinitions.Add("DwgOuter", "inner + circle", Point3d.Origin,
          new GeometryBase[]
          {
            innerRef,
            new ArcCurve(new Circle(new Plane(Point3d.Origin, Vector3d.ZAxis), 1.5)),
          },
          new ObjectAttributes[] { new ObjectAttributes(), new ObjectAttributes() });

        doc.Objects.AddInstanceObject(inner, Transform.Translation(0, 8, 0));
        doc.Objects.AddInstanceObject(inner, Transform.Multiply(
          Transform.Multiply(Transform.Translation(10, 8, 0), Transform.Rotation(0.7, Vector3d.ZAxis, Point3d.Origin)),
          Transform.Scale(Point3d.Origin, 1.5)));
        doc.Objects.AddInstanceObject(outer, Transform.Translation(20, 8, 0));
      });

      // 6. Annotations + nested layers + colors: TEXT, DIMENSION, HATCH, POINT under
      //    FullLayerPath=true (Parent$Child) with one arbitrary-RGB object.
      Author(Path.Combine(importDir, "dwg-annotations.dwg"), null, doc =>
      {
        int parent = doc.Layers.Add("DwgParent", Color.SteelBlue);
        var childLayer = new Layer { Name = "DwgChild", ParentLayerId = doc.Layers[parent].Id, Color = Color.Goldenrod };
        int child = doc.Layers.Add(childLayer);

        doc.Objects.AddText(new Rhino.Display.Text3d("mx dwg", new Plane(new Point3d(0, 0, 0), Vector3d.ZAxis), 3),
          new ObjectAttributes { LayerIndex = parent });

        var dim = LinearDimension.Create(AnnotationType.Aligned, doc.DimStyles.Current,
          new Plane(new Point3d(0, -10, 0), Vector3d.ZAxis),
          Vector3d.XAxis, new Point3d(0, -10, 0), new Point3d(15, -10, 0), new Point3d(7.5, -6, 0), 0.0);
        doc.Objects.AddLinearDimension(dim, new ObjectAttributes { LayerIndex = child });

        var circle = new Circle(new Plane(new Point3d(30, 0, 0), Vector3d.ZAxis), 4);
        Hatch[] hatches = Hatch.Create(circle.ToNurbsCurve(), 0, 0, 1, 0.001);
        Assert.IsNotNull(hatches, "Hatch.Create failed while authoring dwg-annotations.dwg");
        foreach (Hatch h in hatches) doc.Objects.AddHatch(h, new ObjectAttributes { LayerIndex = child });

        doc.Objects.AddPoint(new Point3d(40, 0, 0), new ObjectAttributes
        {
          LayerIndex = child,
          ColorSource = ObjectColorSource.ColorFromObject,
          ObjectColor = Color.FromArgb(10, 200, 90),
        });
      });

      // 7. The curve zoo re-written as ACAD 2000: an older binary revision (AC1015 magic)
      //    through the same reader, and the corpus witness that the Version option plumbs.
      Author(Path.Combine(importDir, "dwg-r2000.dwg"),
        o => o.Version = FileDwgWriteOptions.AutocadVersion.Acad2000, BuildCurveZoo);

      // ----- Export source -----
      AuthorExportSource3dm(Path.Combine(exportDir, "rhino-native-mix-dwg.3dm"));
    }

    static void BuildCurveZoo(RhinoDoc doc)
    {
      doc.Objects.AddCurve(new LineCurve(new Point3d(0, 0, 0), new Point3d(15, 0, 0)));
      doc.Objects.AddCurve(new ArcCurve(new Arc(new Point3d(0, 8, 0), new Point3d(7, 13, 0), new Point3d(15, 8, 0))));
      doc.Objects.AddCurve(new ArcCurve(new Circle(new Plane(new Point3d(25, 4, 0), Vector3d.ZAxis), 3)));
      doc.Objects.AddCurve(new Ellipse(new Plane(new Point3d(38, 4, 0), Vector3d.ZAxis), 6, 3).ToNurbsCurve());
      doc.Objects.AddCurve(NurbsCurve.Create(false, 3, new Point3d[]
      {
        new Point3d(0, 20, 0), new Point3d(5, 25, 3), new Point3d(11, 17, -2), new Point3d(16, 23, 0)
      }));
      doc.Objects.AddCurve(new Polyline(new Point3d[]
      {
        new Point3d(25, 20, 0), new Point3d(32, 20, 0), new Point3d(32, 27, 0)
      }).ToPolylineCurve());

      var pc = new PolyCurve();
      pc.AppendSegment(new LineCurve(new Point3d(40, 20, 0), new Point3d(46, 20, 0)));
      pc.AppendSegment(new ArcCurve(new Arc(new Point3d(46, 20, 0), new Point3d(49, 23, 0), new Point3d(52, 20, 0))));
      doc.Objects.AddCurve(pc);
    }

    static void Author(string outPath, Action<FileDwgWriteOptions> configure, Action<RhinoDoc> build)
    {
      RhinoDoc doc = RhinoDoc.CreateHeadless(null);
      try
      {
        doc.ModelUnitSystem = UnitSystem.Millimeters;
        doc.ModelAbsoluteTolerance = 0.001;

        build(doc);
        Assert.Greater(doc.Objects.Count, 0, $"nothing was built for '{outPath}'.");

        var options = new FileDwgWriteOptions();
        configure?.Invoke(options);

        Assert.IsTrue(FileDwg.Write(outPath, doc, options), $"FileDwg.Write('{outPath}') returned false.");

        TestContext.Progress.WriteLine(
          $"[MXDWG] wrote '{outPath}': {doc.Objects.Count} objects, {new FileInfo(outPath).Length} bytes.");
      }
      finally
      {
        doc.Dispose();
      }
    }

    static void AuthorExportSource3dm(string outPath)
    {
      RhinoDoc doc = RhinoDoc.CreateHeadless(null);
      try
      {
        doc.ModelUnitSystem = UnitSystem.Millimeters;
        doc.ModelAbsoluteTolerance = 0.001;

        int solids = doc.Layers.Add("Solids", Color.SteelBlue);
        int wires = doc.Layers.Add("Wires", Color.Firebrick);
        int facets = doc.Layers.Add("Facets", Color.SeaGreen);
        int notes = doc.Layers.Add("Notes", Color.DarkSlateGray);
        var childLayer = new Layer { Name = "Detail", ParentLayerId = doc.Layers[wires].Id, Color = Color.Purple };
        int detail = doc.Layers.Add(childLayer);

        // Solids + an open trimmed surface: wireframe collapse at the default surfaces-as-curves.
        doc.Objects.AddBrep(Brep.CreateFromBox(new BoundingBox(0, 0, 0, 18, 9, 6)),
          new ObjectAttributes { LayerIndex = solids });
        doc.Objects.AddBrep(Brep.CreateFromCylinder(
          new Cylinder(new Circle(new Plane(new Point3d(35, 0, 0), Vector3d.ZAxis), 5), 12), true, true),
          new ObjectAttributes { LayerIndex = solids });
        var circle = new Circle(new Plane(new Point3d(60, 4, 0), Vector3d.ZAxis), 5);
        Brep[] trimmed = Brep.CreatePlanarBreps(new Curve[] { circle.ToNurbsCurve() }, 0.001);
        Assert.IsNotNull(trimmed, "CreatePlanarBreps failed while authoring rhino-native-mix-dwg.3dm");
        foreach (Brep b in trimmed) doc.Objects.AddBrep(b, new ObjectAttributes { LayerIndex = solids });

        // An extrusion (WriteThickCurves=false default).
        doc.Objects.AddExtrusion(
          Extrusion.Create(new Circle(new Plane(new Point3d(80, 0, 0), Vector3d.ZAxis), 3).ToNurbsCurve(), 10, true),
          new ObjectAttributes { LayerIndex = solids });

        // A mesh: kept by DWG (unlike IGES's default drop).
        doc.Objects.AddMesh(Mesh.CreateFromBox(new BoundingBox(0, 25, 0, 12, 33, 5), 1, 1, 1),
          new ObjectAttributes { LayerIndex = facets });

        // A NURBS curve and a polycurve (SplitPolycurves=true explode).
        doc.Objects.AddCurve(NurbsCurve.Create(false, 3, new Point3d[]
        {
          new Point3d(0, 45, 0), new Point3d(5, 50, 2), new Point3d(11, 42, -2), new Point3d(16, 48, 0)
        }), new ObjectAttributes { LayerIndex = wires });
        var pc = new PolyCurve();
        pc.AppendSegment(new LineCurve(new Point3d(25, 45, 0), new Point3d(32, 45, 0)));
        pc.AppendSegment(new ArcCurve(new Arc(new Point3d(32, 45, 0), new Point3d(35, 48, 0), new Point3d(38, 45, 0))));
        doc.Objects.AddCurve(pc, new ObjectAttributes { LayerIndex = detail });

        // A point, text and a linear dimension.
        doc.Objects.AddPoint(new Point3d(50, 45, 0), new ObjectAttributes { LayerIndex = wires });
        doc.Objects.AddText(new Rhino.Display.Text3d("mx dwg src", new Plane(new Point3d(0, 60, 0), Vector3d.ZAxis), 3),
          new ObjectAttributes { LayerIndex = notes });
        var dim = LinearDimension.Create(AnnotationType.Aligned, doc.DimStyles.Current,
          new Plane(new Point3d(0, 70, 0), Vector3d.ZAxis),
          Vector3d.XAxis, new Point3d(0, 70, 0), new Point3d(18, 70, 0), new Point3d(9, 74, 0), 0.0);
        doc.Objects.AddLinearDimension(dim, new ObjectAttributes { LayerIndex = notes });

        // A block inserted twice.
        int idef = doc.InstanceDefinitions.Add(
          "DwgPeg", "instanced twice", Point3d.Origin,
          new GeometryBase[] { new ArcCurve(new Circle(new Plane(Point3d.Origin, Vector3d.ZAxis), 2)) },
          new ObjectAttributes[] { new ObjectAttributes { LayerIndex = wires } });
        doc.Objects.AddInstanceObject(idef, Transform.Translation(0, 85, 0));
        doc.Objects.AddInstanceObject(idef, Transform.Translation(10, 85, 0));

        // One object whose print color differs from its display color: inert at the default
        // UseColor=USEDISPLAY, a loud diff if that default ever moves.
        var atts = new ObjectAttributes
        {
          LayerIndex = wires,
          ColorSource = ObjectColorSource.ColorFromObject,
          ObjectColor = Color.OrangeRed,
          PlotColorSource = ObjectPlotColorSource.PlotColorFromObject,
          PlotColor = Color.Navy,
        };
        doc.Objects.AddCurve(new LineCurve(new Point3d(30, 85, 0), new Point3d(40, 85, 0)), atts);

        Assert.IsTrue(doc.WriteFile(outPath, new FileWriteOptions { FileVersion = 7 }),
          $"RhinoDoc.WriteFile('{outPath}') returned false.");

        TestContext.Progress.WriteLine(
          $"[MXDWGEX] wrote '{outPath}': {doc.Objects.Count} objects, {new FileInfo(outPath).Length} bytes. " +
          "Regenerate its baseline next: MX_DWGEXPORT_REGEN=rhino-native-mix-dwg.");
      }
      finally
      {
        doc.Dispose();
      }
    }
  }
}
